### PR TITLE
Merge 6.0.x into master

### PR DESCRIPTION
**Pull request by acanby**

### CODE REVIEW

**Comment by acanby** [comment]
I'm not sure how often you do these merges, but I wanted to make sure the fix I did a couple of weeks ago didn't get lost

**Comment by graemerocher** [comment]
Please sign the CLA to have this merged

**Comment by acanby** [comment]
@graemerocher I've signed it; it's waiting for you to sign it apparently ;)

**Comment by graemerocher** [comment]
lol.. how odd

**Pull request merged**
