### PR TITLE
fix for grails/grails-data-mapping#1062

### PR DESCRIPTION
**Pull request by zyro23**
verified locally against the sample app referenced in the issue

### CODE REVIEW

**Comment by ilopmar** [comment]
Can you please include a test for this change? Thanks!

**Comment by puneetbehl** [comment]
It seems like the tests are failing due to another issue #1032 which has been fixed. So could you please rebase your changes with latest 6.1.x branch?

**Comment by zyro23** [comment]
rebased.

**Comment by puneetbehl** [comment]
@zyro23  thanks!

**Pull request merged**
