### PR TITLE
null value support for dynamic finders

### PR DESCRIPTION
**Pull request by demon101**
#1182

### CODE REVIEW

**Comment by graemerocher** [comment]
The test also fails in GORM for Neo4j

**Comment by demon101** [comment]
@graemerocher where I can find tests logs? Is it problem of test or code?

**Comment by graemerocher** [comment]
likely a problem with how the query is translated into the target query for each underlying implementation. The builds are run via Travis, but the logs won't tell you much other than `NullValueEqualSpec` you would need to run the tests for the underlying implementations (`gorm-hibernate5` and `gorm-neo4j`)

**Comment by demon101** [comment]
@graemerocher  strange, I have tested on app with 6.1 snapshot version (hibernate 5), everything works as expected, also NotEqual. Looks like problem in tests

**Comment by zyro23** [comment]
i think the problem is again that `NULL` in sql is never equals meaning that:
```
TestEntity.countByAgeNotEqual(11) == 2
```

fails because `WHERE age <> 11` does not match the rows with `age = NULL`.  

to make the test pass, the semantics/implementation of the `NotEqual` dynamic finder would have to be changed to match `NotEqualOrIsNull` for non-null values, i guess?  
that of course may break existing application code, but this pull request already translates `Equal(null)` to `IsNull` (for all datastores) which both have a different meaning and different expected results in sql, too.

**Pull request merged**
