### PR TITLE
#1039 BlankConstraint is allowing blank values

### PR DESCRIPTION
**Pull request by gonmarques**
This PR fixes issue #1039. Unit tests are included.

### CODE REVIEW

**Comment by jeffbrown** [comment]
How does this PR relate to #1040?

**Comment by jeffbrown** [comment]
This PR has been submitted against the `master` branch, which currently contains code for Grails 4.x which isn't really even under development.  It would probably make more sense to submit this against `3.1.x`, `3.2.x` or `3.3.x` (whichever is the oldest that contains the problem) and we can merge it up the line from there.

**Comment by gonmarques** [comment]
https://github.com/grails/grails-data-mapping/pull/1040 was closed because I inadvertently committed using my local machine username instead of my github username, and was having problems with the Contributor License Agreement signature being recognized.

I will also close this one and apply the changes against `3.x.x` then.

**Comment by jeffbrown** [comment]
Regarding my comment earlier about the `master` branch containing Grails 4.x code, please disregard.  I mistakenly thought this change was in the `grails-core` repo.  I am sorry for the noise.

**Pull request closed without merging**
