### PR TITLE
Support empty list argument in dynamic finder inList only for JPA

### PR DESCRIPTION
**Pull request by demon101**
PR for https://github.com/grails/grails-data-mapping/issues/1212

> is the proposed fix only targeting gorm for sql/hibernate datastores? i think other non-sql databases gorm supports (e.g. mongo) may be just fine with an empty collection argument?
> 
> n.b.: spring-data-jpa seems to work around this with IN (NULL). that also always evaluates to false because NULL in sql is never equal.
> 
> https://jira.spring.io/browse/DATAJPA-606
> https://github.com/spring-projects/spring-data-jpa/blob/2.1.6.RELEASE/src/main/java/org/springframework/data/jpa/provider/PersistenceProvider.java#L103
> https://hibernate.atlassian.net/browse/HHH-8091

### CODE REVIEW

**Comment by zyro23** [comment]
ran the `gorm-hibernate5-6.1.13.BUILD-SNAPSHOT` tests (tck) against this pull-request, here my 2 cents of feedback:
* i think that the tck passes with h2 only because of https://github.com/h2database/h2database/issues/307
  * if you use a different sql database or h2-1.4.193+ with MODE=Oracle, you get the sql exception
* at least for the 6.1.x branch, it looks like the `InList` dynamic finder uses gorm `Restrictions.in`/`Query.in` which is mapped to hibernate criteria with the `HibernateCriterionAdapter`

so perhaps a proper location for the "if collection argument is empty use a collection with a single null element" logic would be around here: https://github.com/grails/grails-data-mapping/blob/v6.1.12/grails-datastore-gorm-hibernate-core/src/main/groovy/org/grails/orm/hibernate/query/AbstractHibernateCriterionAdapter.java#L245

**Comment by demon101** [comment]
@zyro23  we need to go deeper!
https://end3r.github.io/Gamepad-API-Content-Kit/talk/slides/img/go-deeper.jpg 

I have applied your recommendations. 
But I'm already stray in GORM abstractions levels. I hope, you can pull me back out =)

**Comment by demon101** [comment]
Dear @jameskleeh , could you have a look on the PR.  The current (3'rd) solution looks match better the first =)

**Comment by puneetbehl** [comment]
This has been fixed in hibernate 5.4.10.FINAL. So, it should not be a problem with 7.0.3 and the latest 7.0.4

**Pull request closed without merging**
