### PR TITLE
Adding groovy-eclipse support for the data-services `@Service` annotation transformation

### PR DESCRIPTION
**Pull request by sosguthorpe**

### CODE REVIEW

**Comment by sosguthorpe** [comment]
@jameskleeh - Please forgive the direct mention. I'm wondering if you could take a look at this PR. I've raised it against the 6.1.x branch as that's the branch I based the fix on, but the tests seem to fail on async gorm features. I can't figure out where I would have broken that?

**Comment by jameskleeh** [comment]
@sosguthorpe Off hand I don't know. Have you tried running the tests locally with JDK7?

**Comment by sosguthorpe** [comment]
@jameskleeh - I hadn't. Who'd have thought testing the app would reveal a missing transitive dependency that was being excluded in the core project ;-)
Sorry for the unnecessary hassle. The tests pass now.

**Comment by sosguthorpe** [comment]
Given this all passes will this be in the next release or GORM 6.1.x? As an eclipse user it would be great if it was.

**Comment by graemerocher** [comment]
Thanks for the PR

**Pull request merged**
