### PR TITLE
Fix removeFrom for collection of enums.

### PR DESCRIPTION
**Pull request by douglasom**
If you had, say, a OneToMany relationship to an enum type and tried to used the "removeFrom" method you would get the following error:

```
java.lang.NullPointerException: Cannot invoke method isInstance() on null object
	at org.grails.datastore.gorm.GormEnhancer.addAssociationMethods_closure2(GormEnhancer.groovy:187)
```

### CODE REVIEW

**Comment by graemerocher** [comment]
Please provide a unit test with this change

**Comment by graemerocher** [comment]
Could you also provide a pull request for 6.x branch? Since the implementations are very different this is unlikely to get merged up. In 6.x and above there is a trait https://github.com/grails/grails-data-mapping/blob/master/grails-datastore-gorm/src/main/groovy/org/grails/datastore/gorm/GormEntity.groovy#L277

**Comment by douglasom** [comment]
Sure. I'm on it.

**Comment by douglasom** [comment]
The same bug doesn't exist on 6.0.x. Would you like me to open a PR with the unit test for it anyway?

**Comment by graemerocher** [comment]
@douglasom Sounds good

**Comment by douglasom** [comment]
PR for branch 6.0.x: #921.

**Comment by douglasom** [comment]
@graemerocher "The Travis CI build failed" - I ran the tests before and after and I don't think I broke anything. Is there anything else I should do for this pull request?

**Comment by puneetbehl** [comment]
I have manually added the test case for 6.1.x branch  in the commit 53424aa24ba79e2ba53c6fa9cb3f086c7fbfce9c

**Comment by douglasom** [comment]
I closed this PR for the following reasons:

- The newer versions don't have this bug so this patch for older release doesn't seem that important;
-  This PR has stayed on hold for a long time, probably because of the Travis CI build failure which I didn't know how to proceed;

**Pull request closed without merging**
